version: '3.8'

services:
  customer_postgres:
    image: postgres:15
    container_name: customer_postgres
    restart: always
    environment:
      POSTGRES_DB: customers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - customer_pg_data:/var/lib/postgresql/data

volumes:
  customer_pg_data:
