server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: orderservice-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: orderservice
          app: orderservice
          __path__: /var/log/orderservice/*.log

  - job_name: customerservice-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: customerservice
          app: customerservice
          __path__: /var/log/customerservice/*.log
