version: '3.8'

services:
  order_postgres:
    image: postgres:15
    container_name: order_postgres
    restart: always
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - order_pg_data:/var/lib/postgresql/data

volumes:
  order_pg_data:
